import { gateway } from '@ai-sdk/gateway';
import { embed, generateText } from 'ai';
import { getWritingStyle } from './writingStyles.js';

/**
 * Generate embedding for text using Vercel AI Gateway
 * @param {string} text - Text to embed
 * @returns {Promise<Array<number>|null>} - 1536-dimensional vector or null if disabled
 */
export async function generateEmbedding(text) {
  
  if (!process.env.AI_GATEWAY_API_KEY) {
    console.warn('[AI] No AI_GATEWAY_API_KEY found - embeddings disabled');
    return null;
  }

  if (!text) return null;
  
  // Truncate text to avoid token limits
  const truncatedText = text.substring(0, 25000);

  try {
    const { embedding } = await embed({
      model: gateway.embeddingModel('openai/text-embedding-3-small'),
      value: truncatedText,
    });
    
    return embedding;
  } catch (error) {
    console.error('Embedding generation failed:', error.message);
    return null;
  }
}

/**
 * Generate AI-rewritten article (title + content only)
 * Category is extracted from RSS feed, NOT generated by AI.
 * Writing style changes dynamically based on the article's category.
 * 
 * @param {object} article - Original article with title, textContent, and optional category
 * @param {string} article.title - Original headline
 * @param {string} article.textContent - Full article text
 * @param {string} [article.category] - RSS category (determines writing style)
 * @returns {Promise<{title: string, content: string}|null>}
 */
export async function generateArticleContent(article) {
  if (!process.env.AI_GATEWAY_API_KEY) {
    console.warn('[AI] No AI_GATEWAY_API_KEY found - article generation disabled');
    return null;
  }

  if (!article.textContent) return null;

  const { styleName, instructions: styleInstructions } = getWritingStyle(article.category);

  const prompt = `You are a professional news writer for a news publication. Rewrite the following article in your own words. Generate 4 to 6 paragraphs, each paragraph around 40 to 60 words.

WRITING STYLE:
${styleInstructions}

ORIGINAL ARTICLE:
Title: ${article.title}
Content: ${article.textContent.substring(0, 15000)}

Respond in JSON format:
{
  "title": "Your news headline",
  "content": "Your rewritten article (4 to 6 paragraphs, following the writing style above)"
}

STRICT RULES — YOU MUST FOLLOW THESE:
- NEVER mention any source name, news channel, agency, or publication (e.g., BBC, CNN, Reuters, AP, ARY, Geo, Dawn, The News, Al Jazeera, etc.)
- NEVER write "according to reports", "sources say", "as reported by", or any similar attribution phrases
- NEVER reference where the original article came from
- Write as if YOU are the original journalist who covered this story firsthand
- Keep all facts accurate — do not add, invent, or assume any information not in the original
- Write in third person
- The content should be 200 to 350 words
- Do NOT include any media credits, image captions, or social media handles`;

  try {
    const { text } = await generateText({
      model: gateway('openai/gpt-4o-mini'),
      prompt,
    });

    // Parse JSON response
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Invalid JSON response from AI');
    }

    const result = JSON.parse(jsonMatch[0]);

    return {
      title: result.title,
      content: result.content
    };
  } catch (error) {
    console.error(`Article generation failed (style: ${styleName}):`, error.message);
    return null;
  }
}
